#! /usr/bin/env php

<?php
use Symfony\Component\Console\Application;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Input\InputArgument;


require ('vendor/autoload.php');

$App = new Application("Command Line App DEMO", "1.0");
//COMMENT!
$App->register("SayHelloTo") 
	->setDescription("Offer a greeting to the given person.")
	->addArgument("name", InputArgument::OPTIONAL, "Your Name Here!")
	->setCode(function(InputInterface $input, OutputInterface $output)
	{
		$message = "Hello, " . $input->getArgument("name");
		$output->writeln("<comment>{$message}</comment>");
	});

$App->run();