#! /usr/bin/env php

<?php
//Documentation @ http://symfony.com/doc/current/console.html

use Acme\SayHelloCommand;
use Symfony\Component\Console\Application;

require ('vendor/autoload.php');

$App = new Application("Command Line App DEMO", "1.0");

$App->add(new SayHelloCommand);

$App->run();